export const authenticatorSchemas = {
  oidc: [
    {
      key: "provider_uri",
      label: "Provider URI",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "ca_cert",
      label: "CA Certificate",
      type: "textarea",
      required: true,
      rows: 1,
    },
    {
      key: "token_ttl",
      label: "Token TTL",
      type: "text",
      placeholder: "300s",
      required: true,
      rows: 1,
    },
    {
      key: "provider_scope",
      label: "Provider Scope",
      type: "text",
      placeholder: "openid email profile",
      required: true,
      rows: 1,
    },
    {
      key: "client_id",
      label: "Client ID",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "client_secret",
      label: "Client Secret",
      type: "password",
      required: true,
      rows: 1,
    },
    {
      key: "redirect_uri",
      label: "Redirect URI",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "claim_mapping",
      label: "Claim Mapping",
      type: "json",
      required: true,
      rows: 1,
    },
  ],

  jwt: [
    {
      key: "jwks_uri",
      label: "JWKS URI",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "issuer",
      label: "Issuer",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "audience",
      label: "Audience",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "public_keys",
      label: "Public Keys",
      type: "textarea",
      format: "json",
      required: true,
      rows: 10,
    },
    {
      key: "identity.token_app_property",
      label: "Token App Property",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "identity.enforced_claims",
      label: "Enforced Claims",
      type: "array",
      required: true,
      rows: 1,
    },
    {
      key: "identity.claim_aliases",
      label: "Claim Aliases",
      type: "json",
      required: true,
      rows: 1,
    },
    {
      key: "identity.identity_path",
      label: "Identity Path",
      type: "text",
      required: true,
      rows: 1,
    },
  ],

  k8s: [
    {
      key: "kubernetes/api_url",
      label: "Kubernetes API URL",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "kubernetes/ca_cert",
      label: "Kubernetes CA Certificate",
      type: "textarea",
      required: true,
      rows: 1,
    },
    {
      key: "kubernetes/service_account_token",
      label: "Service Account Token",
      type: "password",
      required: true,
      rows: 1,
    },
    {
      key: "ca/key",
      label: "CA Key",
      type: "password",
      required: true,
      rows: 1,
    },
    {
      key: "ca/cert",
      label: "CA Certificate",
      type: "textarea",
      required: true,
      rows: 1,
    },
  ],

  azure: [
    {
      key: "provider_uri",
      label: "Provider URI",
      type: "text",
      required: true,
      rows: 1,
    },
  ],

  aws: [],

  gcp: [],

  ldap: [
    {
      key: "bind_password",
      label: "Bind Password",
      type: "password",
      required: true,
      rows: 1,
    },
    {
      key: "tls_ca_cert",
      label: "TLS CA Certificate",
      type: "textarea",
      required: true,
      rows: 10,
    },
  ],

  certificate: [
    {
      key: "ca_cert",
      label: "CA Certificate",
      type: "textarea",
      required: true,
      rows: 1,
    },
    {
      key: "crl",
      label: "CRL",
      type: "textarea",
      required: true,
      rows: 1,
    },
    {
      key: "crl_url",
      label: "CRL URL",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "identity.host_mode",
      label: "Host Mode",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "identity.trust_domain",
      label: "Trust Domain",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "identity.identity_path",
      label: "Identity Path",
      type: "text",
      required: true,
      rows: 1,
    },
    {
      key: "identity.san_uri",
      label: "SAN URI",
      type: "array",
      required: true,
      rows: 1,
    },
    {
      key: "identity.san_dns",
      label: "SAN DNS",
      type: "array",
      required: true,
      rows: 1,
    },
    {
      key: "identity.san_ip",
      label: "SAN IP",
      type: "array",
      required: true,
      rows: 1,
    },
    {
      key: "identity.cn",
      label: "Common Name",
      type: "text",
      required: true,
      rows: 1,
    },
  ],
};
